# -*- coding: utf-8 -*-
{
    'name': 'MultiWebsite Base Module Canilike',
    'version': '1.0',
    'summary': 'BackEnd customization for all companies and their websites.',
    'description': '',
    'category': 'Website',
    'author': 'Comunitea',
    'website': 'http://www.comunitea.com',
    'license': 'AGPL-3',
    'contributors': [
        'Pavel Smirnov <pavel@comunitea.com>',
        'Rubén Seijas <ruben@comunitea.com>',
    ],
    'depends': [
        'ecommerce_base',
        'breadcrumbs_base',
        'seo_base',
        'multi_company_base',
        'payment_redsys',
        'website_form_builder',
        'portal_multi_access_management',
    ],
    'data': [
        'data/company_data.xml',
        'data/website_data.xml',
        'views/res_company_views.xml',
        'views/website_views.xml',
        'views/product_views.xml',
        'templates/product_recipe.xml',
        'templates/account.xml',
        'templates/snippets.xml',
        'templates/breadcrumbs_bar.xml',
        'templates/header.xml',
        'templates/footer.xml',
        'templates/shop.xml',
        'templates/product.xml',
        'templates/cart.xml',
        'security/ir.model.access.csv',
    ],
    'images': [
        '/static/description/icon.png',
    ],
    'qweb': [
    ],
    'installable': True,
    'application': False,
}
